# Generated by Django 4.0.3 on 2024-03-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Gaming_Chair',
        ),
    ]
