# Generated by Django 5.0.3 on 2024-03-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart_id',
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.cart')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.checkout')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(through='home_page.CheckoutItem', to='home_page.cart'),
        ),
    ]
