# Generated by Django 5.0.3 on 2024-03-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_remove_checkout_cart_id_checkoutitem_checkout_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='items',
        ),
    ]
