# Generated by Django 5.0.3 on 2024-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_remove_checkout_user_checkout_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
