# Generated by Django 5.0.3 on 2024-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_checkout_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.AddField(
            model_name='checkout',
            name='carts',
            field=models.ManyToManyField(related_name='checkouts', to='home_page.cart'),
        ),
    ]
