# Generated by Django 3.2 on 2024-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_alter_cart_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_status',
        ),
    ]
