# Generated by Django 3.2 on 2024-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_auto_20240329_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
