# Generated by Django 3.2 on 2024-03-31 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0007_remove_product_user_id'),
        ('home_page', '0012_alter_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_dashboard.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.member')),
            ],
        ),
    ]
