# Generated by Django 3.2 on 2024-03-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='carts',
            field=models.ManyToManyField(related_name='checkouts', to='home_page.Order'),
        ),
    ]
