# Generated by Django 4.0.3 on 2024-03-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('product_name', models.TextField()),
                ('product_price', models.BigIntegerField(default=0)),
                ('product_size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('new', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('out_of_stock', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('product_image1', models.ImageField(upload_to='product')),
                ('product_image2', models.ImageField(upload_to='product')),
                ('product_image3', models.ImageField(upload_to='product')),
                ('product_image4', models.ImageField(upload_to='product')),
                ('product_image5', models.ImageField(upload_to='product')),
                ('product_description', models.TextField()),
                ('warranty', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_dashboard.admin_member')),
            ],
        ),
        migrations.CreateModel(
            name='Gaming_chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, default='Gaming_Chair', max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.BigIntegerField()),
                ('warranty', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to='Gaming_chair')),
                ('image2', models.ImageField(upload_to='Gaming_chair')),
                ('image3', models.ImageField(upload_to='Gaming_chair')),
                ('image4', models.ImageField(upload_to='Gaming_chair')),
                ('image5', models.ImageField(upload_to='Gaming_chair')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('new', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('out_of_stock', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('Text_1', models.CharField(max_length=30)),
                ('Text_2', models.CharField(max_length=30)),
                ('Text_3', models.CharField(max_length=30)),
                ('Text_4', models.CharField(max_length=30)),
                ('Text_5', models.CharField(max_length=30)),
                ('seller_name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Brand', models.CharField(max_length=50)),
                ('Model_number', models.CharField(max_length=50)),
                ('Angle_Adjustor', models.CharField(max_length=50)),
                ('Rocking_Function', models.CharField(max_length=50)),
                ('Weight_Limit', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Armrest_Type', models.CharField(max_length=50)),
                ('Upholstery_Material', models.CharField(max_length=50)),
                ('Body_Material', models.CharField(max_length=50)),
                ('Adjustable_Armrest', models.CharField(max_length=50)),
                ('Height_Adjustment', models.CharField(max_length=50)),
                ('Backrest_Adjustment', models.CharField(max_length=50)),
                ('Degree_Swivel_Rotation', models.CharField(max_length=50)),
                ('Number_of_Wheels', models.CharField(max_length=50)),
                ('Warranty_Summary', models.CharField(max_length=20)),
                ('Service_Type', models.TextField()),
                ('Covered_in_Warranty', models.TextField()),
                ('Not_Covered_in_Warranty', models.TextField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_dashboard.admin_member')),
            ],
        ),
    ]
