# Generated by Django 4.0.3 on 2024-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0002_alter_product_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.BigIntegerField(default=1),
        ),
    ]
