# Generated by Django 4.0.3 on 2024-03-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_remove_cart_gaming_chair'),
        ('Admin_dashboard', '0005_alter_product_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gaming_chair',
        ),
    ]
