# Generated by Django 3.2 on 2024-03-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0006_delete_gaming_chair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
    ]
